FROM cypress/base:14

ARG HORUS_PROXY_KEY
ENV HORUS_PROXY_KEY=$HORUS_PROXY_KEY

ARG HORUS_COGNITO_CREDENTIALS
ENV HORUS_COGNITO_CREDENTIALS=$HORUS_COGNITO_CREDENTIALS

WORKDIR /app

COPY ./ ./

RUN \
  yarn install && \
  yarn cypress verify
